In [1]:
import numpy as np

In [4]:
l1 =[1,2,3,4]

In [6]:
a1=np.array(l1)

In [7]:
type(a1)

numpy.ndarray

In [8]:
a1.shape

(4,)

In [26]:
ml1= [1,2,3,4]
ml2= [5,6,7,8]
ml3= [9,8,7,6]

ma1=np.array([ml1,ml2,ml3])

In [12]:
ma1.shape

(3, 4)

In [13]:
ma1.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [8, 7, 6]])

In [17]:
ma1[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [20]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [24]:
#dimension of an array
ma1.ndim

2

In [32]:
ma2 = np.array([ml1,[ml2,ml3]])

<ipython-input-32-87402b18ecd3>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  ma2 = np.array([ml1,[ml2,ml3]])


In [33]:
ma2

array([list([1, 2, 3, 4]), list([[5, 6, 7, 8], [9, 8, 7, 6]])],
      dtype=object)

In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [38]:
## array slicing
ma3=np.array([1,2,3,4,5,6,7,8])

print(ma3[1:8:2])

[2 4 6 8]


In [6]:
np.zeros((2,3,4),dtype='int32')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [7]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
# any other number
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [10]:
# full_like
x = np.arange(6,dtype='int32')
np.full_like(x,4)

array([4, 4, 4, 4, 4, 4])

In [12]:
### Random ###
np.random.rand(4,2,3)

array([[[0.8171157 , 0.8281928 , 0.98827085],
        [0.32231988, 0.51618224, 0.94411866]],

       [[0.01718489, 0.62435966, 0.03443516],
        [0.79270909, 0.62957397, 0.04120794]],

       [[0.78387502, 0.8118312 , 0.65938582],
        [0.43427978, 0.33618474, 0.62209385]],

       [[0.00200295, 0.41438926, 0.31522165],
        [0.24146518, 0.13708544, 0.47649273]]])

In [14]:
np.random.random_sample(4)

array([0.24023823, 0.02298607, 0.15675202, 0.57584746])

In [15]:
### Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
l1=[2,3,4,5]
l1*3

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

In [17]:
ma4 = np.array(l1)
ma4*3

array([ 6,  9, 12, 15])

In [20]:
### stacking ###
ma5 = np.array([1,2,3,4])
ma6 = np.array([5,6,7,8])
print(np.vstack([ma5,ma6]))
print("-------------------")
print(np.vstack([ma5,ma6,ma5]))

[[1 2 3 4]
 [5 6 7 8]]
-------------------
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]


In [21]:
# horizontal stacking
np.hstack([ma5,ma6])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1::2])

[1 3 5 7 9]


In [6]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
arr = np.arange(10)

arr.reshape(2,-1)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
# vertical stack
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.vstack([a,b]))
print("*******************")
print(np.hstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
*******************
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [14]:
z = list(range(20))
z[::-1]

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [19]:
rarr = np.random.uniform(5,10,size=(5,3))
print(rarr)

[[8.34778557 9.00491233 7.40856346]
 [6.48398372 8.71481591 9.91414084]
 [7.25627937 7.84114039 6.91054023]
 [8.67791585 7.0539174  5.15810711]
 [6.48648031 6.49979555 5.79979259]]
